---

# roughly this is used as a guide: https://www.netways.de/blog/2018/11/14/ceph-mimic-using-loop-devices-as-osd/


- name: prepare hosts for ceph test deployment
  hosts: all
  become: true
  vars:
    upgrade: True
  tasks:
    - name: update all packages..
      apt:
        update_cache: True
        upgrade: dist
      when: upgrade | bool

    - name: import role for podman
      import_role:
        name: podman

# bootstrap cluster:
#  cephadm bootstrap --mon-ip 10.0.0.2 --cluster-network 10.0.0.0/24 --skip-mon-irgendwas
