---

# roughly this is used as a guide: https://www.netways.de/blog/2018/11/14/ceph-mimic-using-loop-devices-as-osd/


- name: prepare hosts for ceph test deployment
  hosts: all
  vars:
    upgrade: True
  tasks:
    - name: update all packages..
      apt:
        update_cache: True
        upgrade: dist
      when: upgrade | bool

    - name: import role for podman
      import_role:
        name: podman

    - name: create /ceph folder for storage of the osd image files
      file:
        state: directory
        path: /ceph

    - name: create empty img files (if not present)
      command:
        cmd: fallocate -l 40G {{ item }}
        creates: "{{ item }}"
      loop:
        - /ceph/osd1.img
        - /ceph/osd2.img
      
    - name: Create script to add loop devices on startup
      copy:
        dest: /usr/bin/rebloop.sh
        content: |
          #!/bin/bash
          losetup -l -P /dev/loop1 /ceph/osd1.img
          losetup -l -P /dev/loop2 /ceph/osd2.img
    
    - name: add service to add loop devices on startup
      copy:
        dest: /etc/systemd/system/rebloop.service
        content: |
          [Unit]
          Description=Reattach loop device after reboot
          [Service]
          Type=simple
          ExecStart=/bin/bash /usr/bin/rebloop.sh
          [Install]
          WantedBy=multi-user.target
    
    - name: enable service
      systemd:
        daemon_reload: True
        enabled: yes
        name: rebloop.service