---

# https://www.vultr.com/docs/how-to-install-and-use-podman-on-ubuntu-20-04

# "Ich brauch das jetzt... rotz"

- name: install apt key
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{VERSION_ID}}/Release.key
  vars:
    VERSION_ID: '20.04'

- name: create repository files
  copy:
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    content: |
      deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /
  register: podman_repo

- name: update apt caches
  apt:
    update_cache: True
  when: podman_repo is changed

- name: install podman
  apt:
    name:
      - podman
