---


# https://docs.ceph.com/en/pacific/rbd/iscsi-target-cli/
- name: configure iscsi gateway
  hosts: ceph_bootstrap
  become_method: sudo
  become: true
  vars:
    iscsi_service_file: /root/iscsi-gw.yml
    iscsi_service_content:
      service_type: iscsi
      service_id: iscsi
      placement:
        hosts:
          - ceph1
          - ceph2
      spec:
        # This could be misleading... maybe this clears it https://github.com/ceph/ceph/pull/40245#issuecomment-803149481
        # so it should be possible to just "also" store the config for this service inside the rbd pool
        pool: rbd  # RADOS pool where ceph-iscsi config data is stored.
        trusted_ip_list: "192.168.178.210,192.168.178.211,192.168.178.213"
        api_port: '5000' # optional
        api_user: 'admin' # optional
        api_password: 'admin' # optional
        api_secure: false # optional
        # ssl_cert: | # optional

        # ssl_key: | # optional
  tasks:
    - name: Create iscsi service statement
      copy:
        dest: "{{ iscsi_service_file }}"
        content: "{{ iscsi_service_content | to_yaml }}"
      register: iscsi_service_file_created

    - name: Apply service statement if changed
      command:
        cmd: ceph orch apply -i {{ iscsi_service_file }}
      when: iscsi_service_file_created is changed
