---

# prepare
- name: import preparation playbook
  import_playbook: prepare.yml

# bootstrap
## (includes ceph-keys)
- name: import playbook to bootstrap cluster
  import_playbook: bootstrap.yml

# rados-gw object storage
- name: import rados-gw
  import_playbook: rados-gw.yml

- name: import rgw-haproxy
  import_playbook: rgw-haproxy.yml

# create cephfs bar
- name: import cephfs
  import_playbook: cephfs.yml

# rbd
- name: Create and initialize pool for rdb
  import_playbook: rbd.yml

# ceph-iscsi
# - name: import playbook for ceph iscsi
#   import_playbook: ceph-iscsi.yml
