---
# Documentation: https://docs.ceph.com/en/latest/cephadm/rgw/#high-availability-service-for-rgw


# This does not work at the momente due to this bug: https://tracker.ceph.com/issues/51355
# and this leads to failure of prometheus due to: https://tracker.ceph.com/issues/50717
- name: configure rados gateway and dashboard access
  hosts: ceph_bootstrap
  remote_user: adu
  become_method: sudo
  become: true
  tasks:
    - name: save service config
      copy:
        content: |
          service_type: ingress
          service_id: rgw.foo    # adjust to match your existing RGW service
          placement:
            hosts:
              - ceph1
              - ceph2
              # - ceph3
          spec:
            backend_service: rgw.foo      # adjust to match your existing RGW service
            virtual_ip: 192.168.178.209/24       # ex: 192.168.20.1/24
            frontend_port: 8080                 # ex: 8080
            monitor_port: 1967             # ex: 1967, used by haproxy for load balancer status
            # virtual_interface_networks: [ ... ] # optional: list of CIDR networks
            # ssl_cert: |                         # optional: SSL certificate and key
            #   -----BEGIN CERTIFICATE-----
            #   ...
            #   -----END CERTIFICATE-----
            #   -----BEGIN PRIVATE KEY-----
            #   ...
            #   -----END PRIVATE KEY-----

        dest: /root/ha-proxy-service.yml
        mode: 0644
      register: save_service_config

    - name: set rados gateway credentials # noqa no-handler
      command:
        cmd: ceph orch apply -i /root/ha-proxy-service.yml
      when: save_service_config is changed
